name: ts_academy
description: A new Flutter project.
# flutter build appbundle --release   --no-tree-shake-icons
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # AGORA ID: 55a48f67e5ee466a8c5153ee464e32f3
  # agora_rtc_engine: ^4.0.7
  #Logic
  dio: 
  connectivity:  #TODO: Config IOS
  firebase_messaging: #TODO: Config IOS
  firebase_core:  #TODO IOS CONFIG
  permission_handler: 
  either_option: 
  flutter_local_notifications: 
  get_it:
  intl: 

  cached_network_image:

  # socket
  socket_io_client:

  #data presistance
  path_provider: 
  cloud_firestore: 
  shared_preferences: 
  device_info:  #TODO: config ios
  timeago:

  #UI
  overlay_support: 
  # ui_utils:
  reactive_forms:
  flutter_rating_bar: 
  flutter_svg:
  smooth_page_indicator: 
  pinput: 
  percent_indicator: 
  tab_indicator_styler:
  awesome_dialog:
  image_picker:
  syncfusion_flutter_calendar: 
  # fl_chart: ^0.12.0
  syncfusion_flutter_charts: 
  # advance_pdf_viewer:

  #picker
  file_picker: 
  flutter_calendar_week: 

  #database

  logger: 
  provider:

  fluttertoast:
  url_launcher: 
  google_fonts:
  # cupertino_icons: ^1.0.1
  pull_to_refresh:
  modal_bottom_sheet:
  # floating_pullup_card:
  flutter_placeholder_textlines:
  multi_select_flutter:
  toggle_switch: ^1.2.0
  im_stepper: ^0.1.3
  flutter_downloader: ^1.6.1 # TODO integrate ios
  mime: ^1.0.0
  animated_icon_button:
  flat_icons_flutter:
  # flutter_webview_plugin:
  webview_flutter: ^2.0.14
  carousel_slider: ^4.0.0
  flutter_staggered_grid_view: ^0.4.1
#  reactive_extended_text_field: ^0.0.1
#  fancy_shimmer_image: ^2.0.1+1
#  image_cropper: ^1.4.1
  extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image.git
      ref: 47def694fd10481d725bb7b992f491c43599ed5d
#  wechat_assets_picker: ^6.2.4
  persistent_bottom_nav_bar: ^4.0.2
  in_app_purchase: ^2.0.1
  firebase_auth: ^3.3.4
  google_sign_in: ^5.2.1
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  googleapis: ^7.0.0
  flutter_math_fork: ^0.5.0
dev_dependencies:
  flutter_launcher_icons:
  flutter_native_splash: ^1.2.1
  dependency_validator:
  flutter_test:
    sdk: flutter

flutter_icons: #to generate use command $flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/languages/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # fonts:
  # - family: .SF NS Text
  #   fonts:
  #     - asset: assets/fonts/SFNSText.ttf
  # - family: .SF NS Display
  #   fonts:
  #     - asset: assets/fonts/SFNSDisplay.ttf
